### ISSUE TITLE
Running Slackcat

### ISSUE THREAD

**Issue by yeffel** [rlister/slackcat#15]
I have tried to install slackcat and receive the following error when executing it form the command line:

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require': cannot load such file -- httmultiparty (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from ./slackcat:3:in `<main>'

Is there any suggestions on how to resolve this error?

**Comment by rlister** [comment]
@yeffel How did you install? If you installed as `gem install slackcat` (recommended) all dependencies should be fulfilled. If you cloned the repo, you will need to run `bundle install`.

If you did one of these things and the `httpmultiparty` dependency is still not found, it is likely a problem with your ruby installation. Can you check the location of installed gem dependencies?
